/*
 * @Description:
 * @Author: jwzx
 * @Date: 2025-06-20 09:36:06
 * @LastEditTime: 2025-07-04 11:21:20
 * @LastEditors: jwzx
 * @FilePath: \electron-egg\frontend\src\router\elegant\routes.ts
 */
/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    redirect: {
      name: 'png-to-svg'
    },
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'png-to-svg',
    path: '/png-to-svg',
    component: 'layout.base$view.png-to-svg',
    meta: {
      title: 'png-to-svg',
      i18nKey: 'route.png-to-svg',
      localIcon: 'TablerFileTypeSvg',
      constant: true
    }
  },
  {
    name: 'svg-convert-color',
    path: '/svg-convert-color',
    component: 'layout.base$view.svg-convert-color',
    meta: {
      title: 'svg-convert-color',
      i18nKey: 'route.svg-convert-color',
      localIcon: 'MaterialSymbolsFormatColorResetOutline',
      constant: true
    }
  }
];
